# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

gems:
  - jekyll-redirect-from

# Site settings
title: somethingkindawierd.com
email: somethingkindawierd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An iOS developer for Ramsey Solutions
baseurl: ""
domain_name: 'http://somethingkindawierd.com'
url: "http://somethingkindawierd.com"
twitter_username: bejonbee
github_username:  somethingkindawierd
google_analytics: 'UA-4889093-2'
permalink:       /:year/:month/:title.html
timezone: America/Chicago
future: false

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: "" # empty string for all files
            type: stories
        values:
            layout: story
            author: Jonathan Beebe

collections:
  stories:
    output: true
    permalink: /stories/:title.html
